# Generated by Django 5.1.1 on 2025-03-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_shop_alter_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='shop',
            new_name='outlet',
        ),
        migrations.AddField(
            model_name='cart',
            name='calorie_limit',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
