# Generated by Django 5.1.1 on 2025-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_shop_cart_outlet_cart_calorie_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='calorie_limit',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
