# Generated by Django 5.1.6 on 2025-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_calorie_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
