# Generated by Django 5.1.1 on 2025-04-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_species'),
        ('products', '0003_category_species_product_category_product_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.species'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'species')},
        ),
    ]
