# Generated by Django 5.1.1 on 2025-03-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop',
            new_name='outlet',
        ),
        migrations.AddField(
            model_name='order',
            name='total_calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
