# Generated by Django 5.1.1 on 2025-04-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_shop_order_outlet_order_total_calories'),
        ('products', '0003_category_species_product_category_product_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.species'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product', 'species')},
        ),
    ]
