# Generated by Django 5.1.1 on 2025-03-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop',
            new_name='outlet',
        ),
        migrations.AddField(
            model_name='product',
            name='calories_per_100g',
            field=models.PositiveIntegerField(default=1, help_text='Calories per 100g of the product'),
            preserve_default=False,
        ),
    ]
